module.exports = function () {
    return { 
        products: [
            { id: 1, name: "Prateek", category: "CSE", 
                description: "rajpal.prateek@gmail.com",price:9987521466,gender:"Male",dob:"1980-02-04",address:"Sector 11 ,GURUGRAM",doj:"2015-10-10",yoe:13,designation:"Associate Professor", promoted:false },
            { id: 2, name: "Rahul", category: "CSE", 
                description: "rahul98@gmail.com",price:9997853645,gender:"Male",dob:"1981-02-03",address:"Sector 11 ,GURUGRAM",doj:"2013-09-15",yoe:12,designation:"Associate Professor", promoted:false},
            { id: 3, name: "Rakshit", category: "CSE", 
                description: "rakshit67@gmail.com",price:7068545666,gender:"Male",dob:"1975-02-01",address:"Sector 10 ,GURUGRAM",doj:"2017-08-11",yoe:16,designation:"Assosciate Professor", promoted:false},
            
            { id: 4, name: "Pranav", category: "ECE", 
                description: "pranav@gmail.com",price:7068588777,gender:"Male",dob:"1975-09-07",address:"Sector 14 ,Delhi",doj:"2004-05-07",yoe:11,designation:"Professor", promoted:false},
            { id: 5, name: "Prajwal", category: "ECE", 
                description: "prajwal12@gmail.com",price:9874562221,gender:"Male",dob:"1980-03-08",address:"Sector 14 ,GURUGRAM",doj:"2016-05-24",yoe:15,designation:"Professor", promoted:false},
            { id: 6, name: "Porush", category: "ECE", 
                description: "porush_1@gmail.com",price:7530145789,gender:"Male",dob:"1981-04-05",address:"CIVIL LINES,GURUGRAM",doj:"2018-03-01",yoe:14,designation:"Professor", promoted:false},
            { id: 7, name: "Mayank", category: "ME", 
                description: "mayank45@gmail.com",price:7042589631,gender:"Male",dob:"1974-12-05",address:"LAXMI NAGAR ,DELHI",doj:"2015-06-05",yoe:16,designation:"Professor", promoted:false},
            { id: 8, name: "Mudit", category: "ME", 
                description: "mudit@gmail.com",price:8130048584, gender:"Male",dob:"1975-09-15",address:"LAXMAN VIHAR,SEC-5,GURUGRAM",doj:"2011-02-04",yoe:10,designation:"Professor", promoted:false},
            { id: 9, name: "Parth", category: "ME", 
                description: "parth68@gmail.com",price:7989546663,gender:"Male",dob:"1985-01-18",address:"SECTOR 15 PART-A,GURUGRAM",doj:"2010-08-02",yoe:08,designation:"Assistant Professor", promoted:true},
            { id: 10, name: "Sameer", category: "Civil", 
                description: "nagpal.sameer@gmail.com",price:7068546666, gender:"Male",dob:"1982-05-07",address:"SECTOR 15 PART-B,GURUGRAM",doj:"2015-10-05",yoe:10,designation:"Assistant Professor", promoted:true}
            // { id: 11, name: "Vaibhav", category: "Civil", 
            //     description: "almadi.vaibahv@gmail.com",price:9997412354, gender:"Male",dob:"11-10-1980",address:"SECTOR-43,GURUGRAM",doj:"08-09-2006",yoe:12,designation:"Assistant Professor"},
			// { id: 12, name: "Vijender", category: "Civil", 
            //     description: "vijender78@gmail.com",price:8541233668, gender:"Male",dob:"10-10-1978",address:"SECTOR-45,GURUGRAM",doj:"04-03-2009",yoe:17,designation:"Assistant Professor"},
            // { id: 13, name: "Sumit", category: "CSE", 
            //     description: "sumitku@yahoo.com",price:9467854123, gender:"Male",dob:"10-09-1975",address:"SECTOR-45 NEAR FORTIS HOSPITAL,GURUGRAM",doj:"09-01-2017",yoe:14,designation:"nothing"},
            // { id: 14, name: "Ashish", category: "CSE", 
            //     description: "ashishjk@gmail.com",price:8874562235, gender:"Male",dob:"11-12-1976",address:"SECTOR-24 ,GURUGRAM",doj:"09-11-2012",yoe:18,designation:"nothing"},
            // { id: 15, name: "Sandeep", category: "CSE", 
            //     description: "sandeepkl@gmail.com", price:7896612369,gender:"Male",dob:"18-12-1986",address:"RAJIV NAGAR,SECT-14,GURUGRAM",doj:"04-01-2014",yoe:07,designation:"nothing"},
            // { id: 16, name: "Latika", category: "ME", 
            //     description: "latikasrivastav@gmail.com",price:8956663211,gender:"Female",dob:"16-12-1990",address:"Sheetla colony,Sector-11,Gurugram",doj:"15-06-2018",yoe:05,designation:"nothing"},
            // { id: 17, name: "Kalika", category: "ME", 
            //     description: "kalika90@gmail.com",price:9745218863, gender:"Female",dob:"14-05-1991",address:"Ashok vihar,GURUGRAM",doj:"18-05-2017",yoe:04,designation:"nothing"},
            // { id: 18, name: "Sanjay", category: "ME", 
            //     description: "sanjaymishra@gmail.com",price:7215556233, gender:"Male",dob:"24-04-1989",address:"Sector-53,Gurugram",doj:"19-07-2015",yoe:06,designation:"nothing"},
            // { id: 19, name: "Aman", category: "ME", 
            //     description: "amansharma@gmail.com",price:9212566233, gender:"Male",dob:"21-06-1992",address:"Sector-49,Gurugram",doj:"16-05-2017",yoe:05,designation:"nothing"},
            // { id: 20, name: "Machinery's Handbook", category: "ME", 
            //     description: "Book by Erik Oberg and Franklin D. Jones", price: 9874 },
            // { id: 21, name: "Shigley's ME Engineering Design", category: "ME", 
            //     description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 9514 },
            // { id: 22, name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
            //     description: "Book by J.K. Gupta and R.S. Khurmi", price: 7536 },
            // { id: 23, name: "Civil Engineering Formulas", category: "CIVIL", 
            //     description: "Book by Tyler Gregory Hicks", price: 2222 },
            // { id: 24, name: "Theory of Structures", category: "CIVIL", 
            //     description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 3333 },
            // { id: 25, name: "Machinery's Handbook", category: "ME", 
            //     description: "Book by Erik Oberg and Franklin D. Jones", price: 4589 },
            // { id: 26, name: "Shigley's ME Engineering Design", category: "ME", 
            //     description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 6666 },
            // { id: 27, name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
            //     description: "Book by J.K. Gupta and R.S. Khurmi", price: 9999 },
            // { id: 28, name: "Civil Engineering Formulas", category: "CIVIL", 
            //     description: "Book by Tyler Gregory Hicks", price: 8888 },
            // { id: 29, name: "Theory of Structures", category: "CIVIL", 
            //     description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 1100 },
            // { id: 30, name: "Machinery's Handbook", category: "ME", 
            //     description: "Book by Erik Oberg and Franklin D. Jones", price: 5230 },
            // { id: 31, name: "Shigley's ME Engineering Design", category: "ME", 
            //     description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 5241 },
            // { id: 32, name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
            //     description: "Book by J.K. Gupta and R.S. Khurmi", price: 5242 },
            // { id: 33, name: "Civil Engineering Formulas", category: "CIVIL", 
            //     description: "Book by Tyler Gregory Hicks", price: 5269 },
            // { id: 34, name: "Theory of Structures", category: "CIVIL", 
            //     description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 4458 },
           
        ],
        orders: []
    }
}